### ISSUE TITLE
Validation schema not working for params & querystring

### ISSUE THREAD

**Issue by henrifardeau** [elierotenberg/fastify-zod#17]
Hello ! 

I encounter an error when validating parameters or querystring

I register all my schema in my app file like so :

```js
export const { schemas, $ref } = buildJsonSchemas({
  findByIdPartnerSchema,
  findByIdCustomerSchema,
  createPartnerSchema,
  createCustomerSchema,
});

schemas.forEach((schema) => app.addSchema(schema));
```
I try to generate documentation based on the "findByIdCustomerSchema" but this is what i'm getting; (It's working for body validation/documentation)

Maybe i'm doing something wrong 😅

Thank you for your help !
(From france 🇫🇷)

<img width="768" alt="Capture d’écran 2022-05-20 à 10 08 20" src="https://user-images.githubusercontent.com/6832965/169484210-e7af1992-3aad-44ee-94d8-c63ad3ae1f9f.png">
<img width="859" alt="Capture d’écran 2022-05-20 à 10 08 30" src="https://user-images.githubusercontent.com/6832965/169484215-cbe4b060-7439-47e0-966d-58e8f662f523.png">
<img width="663" alt="Capture d’écran 2022-05-20 à 10 09 02" src="https://user-images.githubusercontent.com/6832965/169484219-7752d35c-e899-4e10-ab4f-0a7f170aa8f9.png">
<img width="1437" alt="Capture d’écran 2022-05-20 à 10 11 16" src="https://user-images.githubusercontent.com/6832965/169484304-93ea74f1-f9b3-437b-bcef-7f4492d1aa40.png">

**Comment by henrifardeau** [comment]
EDIT : Sorry my bad, i was using @fastify/swagger instead of fastify-swagger

**Comment by sourcec0de** [comment]
@henrifardeau did you downgrade to get this working?

It looks like https://www.npmjs.com/package/fastify-swagger is actually deprecated.
They recommend upgrading to `@fastify/swagger`

**Comment by elierotenberg** [comment]
Hello,

I'm sorry, as mentioned in #15 for some reason GitHub notifications got lost in my mailbox.

I added support for `querystring` in [1.0.0](https://github.com/elierotenberg/fastify-zod/commit/4602f15029f4c77344d69f3463da2869314d2b14). Does it cover your needs?

**Comment by fukouda** [comment]
@sourcec0de did you ever find a workaround for this? @elierotenberg do we HAVE to use `fastify-swagger` to get queryStrings and params working? I am running into this same issue still

**Comment by fukouda** [comment]
NVM! my solution was to use `@fastify/swagger` in [dynamic mode](https://github.com/fastify/fastify-swagger#dynamic) amd change `swagger` (openAPIV2) in the plugin definition to `openapi`:

```typescript
import { FastifyPluginAsync } from "fastify";
import fp from "fastify-plugin";
import fastifySwagger from "@fastify/swagger";
import fastifySwaggerUi from "@fastify/swagger-ui";

const schemas: FastifyPluginAsync = async (fastify) => {
  await fastify.register(fastifySwagger, {
    openapi: {
      info: {
        title: "API",
        description: "Documentation for our application APIs",
        version: "0.0.1",
      },
      host: "localhost:8080",
      schemes: ["http"],
      consumes: ["application/json"],
      produces: ["application/json"],
      securityDefinitions: {
        apiKey: {
          type: "apiKey",
          name: "Authorization",
          in: "header",
        },
      },
    },
  });

  await fastify.register(fastifySwaggerUi, {
    routePrefix: "/documentation",
  });
};

export default fp(schemas);

```
