### ISSUE TITLE
typed-jest-expect dependencies should in devDependencies?

### ISSUE THREAD

**Issue by skimhugo** [elierotenberg/fastify-zod#25]
<img width="461" alt="image" src="https://user-images.githubusercontent.com/9862730/188351291-b7c082a0-d50c-451c-9e9c-ec25bd014b8c.png">

**Comment by elierotenberg** [comment]
Thank you!
It has been fixed in 4b1abf7971113f20fed5ff2013d7b5f06faeb782 and released in 1.2.0.
