### ISSUE TITLE
@openapitools/openapi-generator-cli should in devDependencies

### ISSUE THREAD

**Issue by skimhugo** [elierotenberg/fastify-zod#27]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/9862730/190986101-9287f0eb-d7fa-457a-8b50-b6078853e83e.png">

**Comment by arnorhs** [comment]
Thish should probably be in peerDependencies, right?

**Comment by elierotenberg** [comment]
Thanks, this has been fixed in e4b5ce75cef655f20942f97bcc3c86caf2a614a1.
