### ISSUE TITLE
Unable to add schema to Fastify when targeting openapi schema

### ISSUE THREAD

**Issue by JRGranell** [elierotenberg/fastify-zod#3]
Hi @elierotenberg ,

Thanks for creating the library, I've been using it to pass my Zod schema to Fastify using JSON schema and it works really nicely. However I when I try to validate the openapi schema that is produced it is not valid. This could be because in `buildJsonSchema` I am not explicitly targeting openapi so it defaults to JSON schema.

However when I target openapi instead of JSON schema, Fastify blows up as it's not valid. I'm just wondering if there is a way for the JSON schema to be passed to Fastify so it can validate the incoming params etc, but for the swagger to use the open api version?

To reproduce the issue add a schema to Fastify that targets openapi.

Any help would be appriciated,

**Comment by JRGranell** [comment]
Closing as this is not an issue with this lib. The source of the problem was that you can use some features with Zod (such as `.positive()` that will output `inclusiveMinimum` in JSON schema (v7) that is not compatible with Open API definitions. This article provides a comprehensive overview of some of the limitations of trying to use JSON schema with Open API https://phil.tech/2019/update-openapi-json-schema/

**Comment by elierotenberg** [comment]
Thanks for your comment and help!
Please let me know if I can be of any help. Using this library myself in several projects, I have indeed encountered a lot of tricky edge cases, e.g. const / enums. I also found a way around them, but I'd be very happy to have your feedback as well.
