### ISSUE TITLE
Querystring on GET routes shows all schemas as parameters in Swagger

### ISSUE THREAD

**Issue by hugorplobo** [elierotenberg/fastify-zod#40]
Hi, when I register this schema:
```ts
import { z } from "zod";

export const loginUserSchema = z.object({
  username: z.string(),
  password: z.string(),
});

export const loginUserResponseSchema = z.object({});
```

And try to use it, like this:
```ts
fastify.zod.get("/login", {
    operationId: "loginUser",
    // params: "loginUserSchema",
    querystring: "loginUserSchema",
    response: {
      200: "loginUserResponseSchema",
    },
  }, async (_req, _rep) => {
    return {};
  });
```
I get this result in Swagger UI:
![image](https://user-images.githubusercontent.com/53958114/236657656-105ef005-bf45-4c71-90f5-5f7246a6d806.png)

What am I doing wrong? How to set querystring params correctly?

**Comment by sirgallifrey** [comment]
@hugorplobo It happened to me as well, what I think solved for me was settings the target to openApi3
```
jsonSchemas: buildJsonSchemas(Schemas, { target: "openApi3"}),
```

**Comment by hugorplobo** [comment]
Thank you! :D

**Comment by myroslavsuprun** [comment]
If anyone still has the same issue, here's what helped for me:

I updated the target for jsonSchemas as shown above and I also added to the _fastify/swagger_  options the _openapi_ field.
`{
openapi: {}
}`
