### ISSUE TITLE
Support for nullable field

### ISSUE THREAD

**Issue by sergey-pogranichnyi** [elierotenberg/fastify-zod#50]
.nullable() zod property doesn't work correctly.

Reproducible case:
```ts
// Define custom messages
import { z } from 'zod';
import fastify from 'fastify';
import { buildJsonSchemas, FastifyZod, register } from 'fastify-zod';

const TodoItemId = z.object({
  id: z.string().or(z.null()),
});

const models = {
  TodoItemId,
};

declare module 'fastify' {
  interface FastifyInstance {
    readonly zod: FastifyZod<typeof models>;
  }
}

(async () => {
  // Then configure fastify
  const f = fastify(
  });

  await register(f, {
    jsonSchemas: buildJsonSchemas(models),
    swaggerOptions: {
      openapi: {
        info: {
          title: '1',
          description: '2',
          version: '2.0.0',
        },
      },
    },
    swaggerUiOptions: {
      routePrefix: '/doc',
      staticCSP: true,
    },
  });

  f.zod.get(
    '/todo',
    {
      operationId: '',
      response: {
        200: 'TodoItemId',
      },
    },
    async () => {
      return {
        id: '1',
      };
    },
  );
  await f.listen({
    port: 3000,
  });
})();
```

Which produces incorrect type for the schema:
<img width="368" alt="image" src="https://github.com/user-attachments/assets/40a69c74-8fe7-478c-ad9f-66248e4bf722">

**Comment by zapotinschii** [comment]
Try to use openapi v3.1, i believe by default is openapi v3, and prabably v3 don't support nullable
![image](https://github.com/user-attachments/assets/99e68d8e-a458-420b-9183-fd2606618bf5)

**Comment by sergey-pogranichnyi** [comment]
> Try to use openapi v3.1, i believe by default is openapi v3, and prabably v3 don't support nullable ![image](https://private-user-images.githubusercontent.com/118645444/371503807-99e68d8e-a458-420b-9183-fd2606618bf5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2ODQ5NTEsIm5iZiI6MTcyNzY4NDY1MSwicGF0aCI6Ii8xMTg2NDU0NDQvMzcxNTAzODA3LTk5ZTY4ZDhlLWE0NTgtNDIwYi05MTgzLWZkMjYwNjYxOGJmNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQwODI0MTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZWE4NGEzOWQyZTc0NzcxNmFlMGY0NTczNDRkNmJiZjM0MzUzOThhNWY5ZjE1YzY5MGM0ZjM5ZWQ1NWQ2NTg5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.p5geE02JjgzFOjH3buCDK6eGy9Md9spRpZlJP8q6Bn8)

Thanks, it helped:
```ts
  await register(f, {
    jsonSchemas: buildJsonSchemas(models),
    swaggerOptions: {
      openapi: {
        openapi: '3.1.0',
        info: {
          title: '1',
          description: '2',
          version: '2.0.0',
        },
      },
    },
    swaggerUiOptions: {
      routePrefix: '/doc',
      staticCSP: true,
    },
  });
```
